#!/bin/bash
farm_folder='/storage/chroot/farm/'
config_folder='/etc/chroot'

echo -e 'Install kernel'
apt-get -t wheezy-backports install linux-image-3.14-0.bpo.1-amd64

echo -e 'Install packages'
apt-get install build-essential python-dev python-pkg-resources python-setuptools  python-ipaddr
easy_install pip
pip install fabric cuisine sh config

echo -e 'Create structure'
mkdir -p  $config_folder
mkdir -p  $farm_folder
echo -e 'Copy files'
cp -r  ship/etc/*  $config_folder
unlink /usr/bin/chrootmn
ln -s $config_folder/scripts/chrootmn /usr/bin/

echo -e 'Compile nsender and unshare'
cd /tmp
curl https://www.kernel.org/pub/linux/utils/util-linux/v2.24/util-linux-2.24.tar.gz | tar -zxf-

cd /tmp/util-linux-2.24
./configure --without-ncurses
make nsenter
make unshare
cp nsenter $config_folder/bin
cp unshare $config_folder/bin

echo -e 'Finish'
