#!/bin/bash
farm_folder='/storage/ship/farm/'
config_folder='/etc/ship'

echo -e 'Create structure'
mkdir -p  $config_folder
mkdir -p  $farm_folder
echo -e 'Copy files'
cp -r  etc/*  $config_folder
unlink /usr/bin/shipmn
ln -s $config_folder/scripts/shipmn /usr/bin/

echo -e 'Compile nsender and unshare'
cd /tmp
curl https://www.kernel.org/pub/linux/utils/util-linux/v2.24/util-linux-2.24.tar.gz | tar -zxf-

cd /tmp/util-linux-2.24
./configure --without-ncurses
make nsenter
make unshare
cp nsenter $config_folder/bin
cp unshare $config_folder/bin

echo -e 'Finish'
