#!/bin/bash
farm_folder='/storage/ship/farm/'
config_folder='/etc/ship'

echo 'deb http://ftp.debian.org/debian/ wheezy-backports main non-free contrib' >> /etc/apt/sources.list
apt-get update

echo -e 'Install kernel'
apt-get -t wheezy-backports install linux-image-amd64 

echo -e 'Install packages'
apt-get install build-essential python-dev python-pkg-resources python-setuptools  python-ipaddr curl
easy_install pip
pip install ipcalc netaddr sh config

echo -e 'Create structure'
mkdir -p  $config_folder
mkdir -p  $farm_folder
echo -e 'Copy files'
cp -r  etc/*  $config_folder
unlink /usr/bin/shipmns
ln -s $config_folder/scripts/shipmns /usr/bin/shipmn

echo -e 'Compile nsender and unshare'
cd /tmp
curl https://www.kernel.org/pub/linux/utils/util-linux/v2.24/util-linux-2.24.tar.gz | tar -zxf-

cd /tmp/util-linux-2.24
./configure --without-ncurses
make nsenter
make unshare
cp nsenter $config_folder/bin
cp unshare $config_folder/bin

echo -e 'Finish'



echo -e 'OpenVswitch config:'
echo -e 'ovs-vsctl add-br ovsbr'
echo -e 'ovs-vsctl add-port ovsbr eth0'
echo -e ''
echo -e 'cat /etc/network/interfaces'
echo -e 'auto eth0'
echo -e 'iface eth0 inet static'
echo -e 'address 0.0.0.0'
echo -e 'auto ovsbr'
echo -e 'iface ovsbr inet static'
echo -e '        pre-up /etc/init.d/openvswitch-switch start'
echo -e '        ovs_type OVSBridge'
echo -e '        ovs_ports eth0 ovsbr'
echo -e '        address 192.168.79.131'
echo -e '        netmask 255.255.255.0'
echo -e '        broadcast 192.168.79.255'
echo -e '        gateway 192.168.79.2'
echo -e '        dns-nameservers 192.168.79.2'
echo -e '        up /sbin/ifconfig $IFACE up'
